tests/main: account for expected failures when running with SNAP_REEXEC=1
Account for expected failures when running with SNAP_REEXEC on unsupported
distros.

Signed-off-by: Maciej Borzecki <maciej.borzecki@canonical.com>

diff --git a/tests/main/command-chain/task.yaml b/tests/main/command-chain/task.yaml
--- a/tests/main/command-chain/task.yaml
+++ b/tests/main/command-chain/task.yaml
@@ -26,6 +26,20 @@ execute: |
     MATCH '^CHAIN_1_RAN=1$' < "$ENVDUMP"
     MATCH '^CHAIN_2_RAN=1$' < "$ENVDUMP"
 
+    if [ "$SNAP_REEXEC" = "1" ] && (os.query is-fedora || os.query is-amazon-linux || os-query is-opensuse-tumbleweed) ; then
+        # we now support explicitly enabling reexec, which may fail when
+        # snap-confine is under /usr/libexec/snapd, on those systems expect a
+        # very specific error
+        if command-chain.hello > err.out 2>&1; then
+            echo "unexpected success"
+            cat err.out || true
+            exit 1
+        fi
+
+         MATCH "running from unexpected location:" < err.out
+         exit 0
+    fi
+
     echo "Test that command-chain runs for apps"
     [ "$(command-chain.hello)" = "chain1 chain2 hello" ]
 
diff --git a/tests/main/install-sideload/task.yaml b/tests/main/install-sideload/task.yaml
--- a/tests/main/install-sideload/task.yaml
+++ b/tests/main/install-sideload/task.yaml
@@ -29,6 +29,21 @@ execute: |
 
     echo "Sideloaded snap executes commands"
     snap install --dangerous ./test-snapd-tools_1.0_all.snap
+
+    if [ "$SNAP_REEXEC" = "1" ] && (os-query is-fedora || os-query is-amazon-linux || os-query is-opensuse-tumbleweed) ; then
+        # we now support explicitly enabling reexec, which may fail when
+        # snap-confine is under /usr/libexec/snapd, on those systems expect a
+        # very specific error
+        if test-snapd-tools.success > err.out 2>&1; then
+            echo "unexpected success"
+            cat err.out || true
+            exit 1
+        fi
+
+        MATCH "running from unexpected location:" < err.out
+        exit 0
+    fi
+
     test-snapd-tools.success
     [ "$(test-snapd-tools.echo Hello World)" = "Hello World" ]
 
diff --git a/tests/main/snap-run-hook/task.yaml b/tests/main/snap-run-hook/task.yaml
--- a/tests/main/snap-run-hook/task.yaml
+++ b/tests/main/snap-run-hook/task.yaml
@@ -20,6 +20,20 @@ execute: |
 
     echo "Test that snap run can call valid hooks"
 
+    if [ "$SNAP_REEXEC" = "1" ] && (os.query is-fedora || os.query is-amazon-linux || os-query is-opensuse-tumbleweed); then
+        # with opt in for snap reexec the test complexity is greatly increased,
+        # skip it on systems where we know it does not work, so just verify
+        # expected failure and exit
+        if snap run --hook=configure basic-hooks > err.out 2>&1; then
+            echo "unexpected success"
+            cat err.out || true
+            exit 1
+        fi
+
+        MATCH "running from unexpected location:" < err.out
+        exit 0
+    fi
+
     if ! output="$(snap run --hook=configure basic-hooks)"; then
         echo "Failed to run configure hook"
         exit 1
diff --git a/tests/main/writable-areas/task.yaml b/tests/main/writable-areas/task.yaml
--- a/tests/main/writable-areas/task.yaml
+++ b/tests/main/writable-areas/task.yaml
@@ -19,6 +19,21 @@ execute: |
     snap install --dangerous data-writer_1.0_all.snap
 
     echo "Apps can write to writable areas"
+
+    if [ "$SNAP_REEXEC" = "1" ] && (os.query is-fedora || os.query is-amazon-linux || os-query is-opensuse-tumbleweed) ; then
+        # we now support explicitly enabling reexec, which may fail when
+        # snap-confine is under /usr/libexec/snapd, on those systems expect a
+        # very specific error
+        if data-writer.app > err.out 2>&1 ; then
+            echo "unexpected success"
+            cat err.out || true
+            exit 1
+        fi
+
+        MATCH "running from unexpected location:" < err.out
+        exit 0
+    fi
+
     data-writer.app
     [ -f /var/snap/data-writer/x1/from-app ]
     [ -f /var/snap/data-writer/common/from-app ]
